# Array Slicing

## Array Slicing: One dimensional 

In [10]:
import numpy as np

#Array 10 valori che parte da 5 fino a 15 (escluso)

x = np.arange(5,15,1)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
#Primi sei valori
x[:6]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
#Elementi dopo l'indice 3
x[3:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [18]:
#Subarray con valori 8,9,10,11,12
x[3:8]

array([ 8,  9, 10, 11, 12])

In [20]:
#Un elemento ogni 3 partendo dal primo
x[::3]

array([ 5,  8, 11, 14])

In [24]:
#Un elemento ogni 3 partendo dal terzo
x[3::3]

array([ 8, 11, 14])

## Array Slicing: Multi dimensional

### es2a

In [29]:
np.random.seed(0)

es2a = np.random.randint(16, size=(4,6))
es2a

array([[12, 15,  5,  0,  3, 11],
       [ 3,  7,  9,  3,  5,  2],
       [ 4,  7,  6,  8,  8, 12],
       [10,  1,  6,  7,  7, 14]])

In [30]:
#Prime tre righe e prime tre colonne
es2a[:3, :3]

array([[12, 15,  5],
       [ 3,  7,  9],
       [ 4,  7,  6]])

In [37]:
#Seconda e terza riga, quarta, quinta e sesta colonna
es2a[1:3, 3:]

array([[ 3,  5,  2],
       [ 8,  8, 12]])

In [54]:
#Elementi dopo il terzo elemento
es2a[0::,3:]

array([[ 0,  3, 11],
       [ 3,  5,  2],
       [ 8,  8, 12],
       [ 7,  7, 14]])

In [47]:
#Invertire l'ordine delle sole righe
es2a[0:,::-1]

array([[11,  3,  0,  5, 15, 12],
       [ 2,  5,  3,  9,  7,  3],
       [12,  8,  8,  6,  7,  4],
       [14,  7,  7,  6,  1, 10]])

In [49]:
#Invertire l'ordine delle sole colonne
es2a[::-1]

array([[10,  1,  6,  7,  7, 14],
       [ 4,  7,  6,  8,  8, 12],
       [ 3,  7,  9,  3,  5,  2],
       [12, 15,  5,  0,  3, 11]])

### es2b

In [63]:
np.random.seed(0)

es2b = np.random.randint(31, size= (2, 5, 5))
es2b

array([[[12, 15, 21,  0,  3],
        [27,  3,  7,  9, 19],
        [21, 18,  4, 23,  6],
        [24, 24, 12, 26,  1],
        [ 6,  7, 23, 14, 24]],

       [[17,  5, 25, 13,  8],
        [ 9, 20, 19, 16, 19],
        [ 5, 30, 15, 15,  0],
        [18,  3, 24, 17, 19],
        [29, 19, 19, 14,  7]]])

In [71]:
#Selezionare il primo subarray, poi prendere le prime 2 righe e le colonne dalla seconda alla quarta
es2b[0, :2, 1:4]

array([[15, 21,  0],
       [ 3,  7,  9]])

In [78]:
#Selezionare da entrambi i subarray le prime due righe e prime due colonne e invertire righe e colonne
es2b[:2, :2]

a = es2b[:2, :2]
b = a[::-1, ::-1]

print("Matrice",b)

Matrice [[[ 9 20 19 16 19]
  [17  5 25 13  8]]

 [[27  3  7  9 19]
  [12 15 21  0  3]]]


## Array Slicing: Subarrays as no-copy views

In [80]:
es3 = np.random.randint(21, size = (3,3))

#Visualizzare es3
es3

array([[ 2,  0,  0],
       [ 4,  5,  6],
       [ 8, 20, 17]])

In [84]:
#Estrarre il subarray formato dalla seconda riga e visualizzarlo
es3_sub = es3[1, :3]
es3_sub

array([4, 5, 6])

In [86]:
#Moltiplicare per 3 tutti gli elementi della seconda colonna di es3
es3*3

es3_sub
#es3_sub non è cambiato perchè il suo valore è rimasto memorizzato dal comando "es3_sub = es3[1, :3]"

array([4, 5, 6])

In [101]:
#Estrarre il subarray formato dalla terza colonna di es3 come copia
es3_sub_copy = es3[0:3, 2:].copy()

es3_sub_copy

array([[ 0],
       [ 6],
       [17]])

In [102]:
#Sommare 10 a tutti gli elementi di es3-sub-copy e visualizzare
es3_sub_copy = es3_sub_copy+10

es3_sub_copy

array([[10],
       [16],
       [27]])

In [103]:
#es3 non contiene le modifiche del punto 6
es3

array([[ 2,  0,  0],
       [ 4,  5,  6],
       [ 8, 20, 17]])

## Array Concatenation and Splitting

In [109]:
#Creare una lista es4 di 36 valori interi crescenti partendo da 1

es4 =list(range(1, 37))
es4

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36]

In [116]:
#Trasformarlo in un array di dimensione 6x6
es4_arr = np.array(es4)
es4_matrice =np.reshape(es4_arr, [6,6])

es4_matrice

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [123]:
#Estrarre tre subarray di dimensione 2x2 dalle prime due colonne

sub1 = es4_matrice[0:2, 0:2]
sub2 = es4_matrice[2:4, 0:2]
sub3 = es4_matrice[4:6, 0:2]

print("sub1", sub1)
print("sub2", sub2)
print("sub3", sub3)

sub1 [[1 2]
 [7 8]]
sub2 [[13 14]
 [19 20]]
sub3 [[25 26]
 [31 32]]


In [133]:
#Concatenarli con axis = 0

con_axis0 = np.concatenate([sub1,sub2,sub3])
con_axis0

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [126]:
#Concatenarli con axis = 1

con_axis1 = np.concatenate([sub1,sub2,sub3], axis =1)
con_axis1

array([[ 1,  2, 13, 14, 25, 26],
       [ 7,  8, 19, 20, 31, 32]])

In [132]:
#Da es4_matrice estrarre un subarray formato dalle prime due righe (sub4)

sub4 = es4_matrice[0:2, 0::]
sub4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [162]:
#Concatenare sub1 a sub4 con hstack

sub4_sub1 =np.hstack([sub1, sub4])

sub4_sub1

array([[ 1,  2,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  7,  8,  9, 10, 11, 12]])

In [156]:
#Trasformo sub4 da 2x6 a 6x2

sub4_trasf =sub4.reshape((6,2))

In [157]:
#Concatenate sub1, sub2 e sub3 a formare un nuovo array 6x2
sub5 = np.concatenate([sub1, sub2, sub3])

sub5

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [160]:
#Concateno sub4_trasf con sub5 con hstack per formare una matrice 6x4
np.hstack([sub4_trasf,sub5])

array([[ 1,  2,  1,  2],
       [ 3,  4,  7,  8],
       [ 5,  6, 13, 14],
       [ 7,  8, 19, 20],
       [ 9, 10, 25, 26],
       [11, 12, 31, 32]])

In [163]:
#Concateno sub4_trasf con sub5 con vstack per formare una matrice 12x2
np.vstack([sub4_trasf,sub5])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])