# Primo Esercizio

In [ ]:
#Import della libreria
import numpy as np

##Creare array (x, dtype =int) con x= lunghezza array e riempirla con:

In [ ]:
#Zero
np.zeros(50, dtype =int)

In [ ]:
#Uno
np.ones((2, 5), dtype = int)

In [ ]:
#Numero definito
np.full((3, 3), 12.34)

In [ ]:
np.arange(start =6, stop =45, step= 4, dtype= int)

In [ ]:
np.linspace(0, 100, 5)

In [ ]:
np.random.random((1,10))

In [ ]:
np.random.normal(size = (2, 10))

# Secondo Esercizio

In [ ]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

print("dtype:", x3.dtype)

print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

In [ ]:
#Primo punto
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

In [ ]:
#Secondo punto, terzo punto e quarto punto
x1 = np.random.randint(2, size= (4,5)) 

print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

print("Matrice:", x1)

#Il primo paramentro di random.radint genera un intero casuale da 0 a x, con x = intero inserito.

In [ ]:
#Quinto punto

x1 = np.random.randint(100, size= (4,5)) 
print("Matrice:", x1)

#Visualizzo valori casuali compresi tra 0 e 100

# Terzo Esercizio

In [83]:
import numpy as np

es1 = np.random.randint(9, size = (3, 5))
print("Matrice:", es1)

Matrice: [[6 3 2 8 1]
 [4 0 8 3 5]
 [5 1 7 8 6]]


# Lavoro su questa matrice casuale
# Matrice: 
# [6 3 2 8 1]
# [4 0 8 3 5]
# [5 1 7 8 6]

In [ ]:
#Seleziono tutti i "3"

es1[0,1]

In [ ]:
es1[1,3]

In [ ]:
#Ora con la forma negativa

es1[-3, -4]

In [ ]:
es1[-2, -2]

In [110]:
#Seleziono primo elemento della seconda riga

es1[1,0]

4

In [111]:
#Seleziono quinto elemento della prima riga

es1[0,4]

1

In [109]:
#Seleziono secondo elemento della seconda colonna

es1[1,1]

0

In [112]:
#Seleziono quarto elemento della terza colonna
#NON c'è perchè la matrice è 3x5



In [115]:
#Sommo 10 all'elemento es1[0,0]
es1[0,0]+10

16

In [ ]:
#Sottraggo 5 all'elemento es1[3,2]

#NON posso perchè es1[3,2] indica l'estrazione del terzo valore contenuto nella riga 4
#questo perchè il primo elemento della matrice non viene indicato con es1[1,1] ma con es1[0,0]
#Essendo la nostra una matrice 3x5 la riga 4 non è presente.

In [120]:
es1[2,0] = es1[0,0] + es1[1,0]

#Ovvero es1[2,0]= 6 + 4 = 10

es1[2,0]

10